apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: almerico/test1
    workspace: .
    docker:
      dockerfilePath: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - Deployment.yml
